name = "aws_credentials_gleam"
version = "0.0.1"
target = "erlang"

description = "Type-safe AWS credentials management for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aws-beam", repo = "aws-erlang" }
links = [{ title = "Sponsor", href = "https://github.com/sponsors/aws-beam" }]

[dependencies]
gleam_stdlib = ">= 0.62.0 and < 1.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
