name = "aws_credentials_gleam"
version = "0.0.2"
target = "erlang"

description = "Type-safe AWS credentials management for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "SundayPowerEndre", repo = "aws_credentials_gleam" }

[dependencies]
gleam_stdlib = ">= 0.62.0 and < 1.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
aws_credentials = "0.3.5"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
